/*
 * This source file was generated by the Gradle 'init' task
 */
package com.evanxu;

import java.util.logging.Logger;

import com.sun.tools.javac.Main;

public class App {
	
	/** Logger. */
	private static final Logger LOGGER = Logger.getLogger(Main.class.getName());

    public static void main(String[] args) {
    	LOGGER.info(() -> "App starting");
    }
}
